name: Convert FIT and Upload to Drive

on:
  push:
    paths:
      - 'fit_files/*.fit'
  workflow_dispatch:

jobs:
  convert-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Inject secrets into env
      # Pull your Google secrets from GitHub and set them as env variables
      run: echo "Setting GDRIVE vars"
      env:
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }} 
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

    - name: Convert and Upload
      # The environment variables above won't persist automatically across steps
      # So you can either do the same approach in-line or combine steps.
      run: |
        echo "Running convert_and_upload.py..."
        python convert_and_upload.py
      env:
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
